---

- name: Including variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
  when: ssh_config is not defined
