---

- name: Including OS specific variables
  include_vars: "{{ lookup('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
      paths:
        - 'vars'
